### ISSUE TITLE
navigateToHomeRoute() issue with Start Controller?

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#1037]
I was wondering should the router's `navigateToHomeRoute()` function consider whether the start controller is enabled, and specifically if it's being forced?  Without this it appears possible to click on a home icon and get routed to an un-intended menu, rather than the landing page.

**Comment by moloko** [comment]
This is a good point... we would normally hide the home/back button on any start pages using CSS - but appreciate that is going to be tough to do if you're using the AT.

Or are you referring to what happens when you're in a standard content page and select the home/back button? In that instance I would generally want the user to be sent back to the main menu and not the 'start page' - mainly because we used the start page as something we want the user to be shown before the menu and then generally never seen again.

Maybe the way to address this is instead to allow for more control over when the home/back button is shown and over what clicking this button does (with the default being to go back in the history, as it does now)?

**Comment by moloko** [comment]
Now being addressed in #1152 I think?

**Comment by brian-learningpool** [comment]
Yes, this is resolved with the new `_isMenuDisabled` attribute.
