### ISSUE TITLE
latest version of contrib-hotgraphic breaks the adapt CLI

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1043]
I'm guessing it originates from [this addition](https://github.com/adaptlearning/adapt-contrib-hotgraphic/blob/master/bower.json#L19-L21) to bower.json... but quite why it breaks the CLI so badly I don't know.

Please could someone pick this up an investigate as a priority?

**Comment by davewallace** [comment]
i ran into this issue, but the error reported in terminal was for -narrative. i added v2.0.4 for the version number instead of * for -hotgraphic (thanks @lc-thomasberger ) and that didn't fix it.

with a clean repo clone i tried the above again with v2.0.4 for -narrative, still didn't fix the issue.

with another clean repo clone i tried the above again for both -narrative and -hotgraphic - problem solved.

**Comment by moloko** [comment]
@davewallace  it's because hotgraphic's bower.json has a dependency on narrative. 
I've just tried the manual install, changing only the reference to hotgraphic in adapt.json and that's working fine for me...
