### ISSUE TITLE
Question components - show remaining number of attempts should default to false

### ISSUE THREAD

**Issue by ryan-lynch** [adaptlearning/adapt_framework#1110]
For question components, in the schema the number of attempts default is 1. It doesn't make sense that displaying the number of remaining attempts is set to true by default. 

This would affect the following components:

I believe this would affect components: GMCQ, Matching, MCQ, text input and slider.

**Comment by moloko** [comment]
In the properties.schema for all of these, the `default` of `_shouldDisplayAttempts` is set to `false`

The logic for handling this is in [buttonsView.js](https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/views/buttonsView.js#L112-L143) and looks to be set up so that it will not try to show 'attempts remaining' unless `_shouldDisplayAttempts` is explicitly set to `true`

**Comment by ryan-lynch** [comment]
The ariaLabel's for each question component should have an input type of QuestionButton but instead have "Text". I'll update as part of this.

**Comment by brian-learningpool** [comment]
Hi @ryan-lynch, can you create the "QuestionButton" issue as a separate ticket please?  I'm closing this one as per the title it's already implemented.
