### ISSUE TITLE
Question components button ariaLabels should have an inputType of QuestionButton

### ISSUE THREAD

**Issue by ryan-lynch** [adaptlearning/adapt_framework#1111]
As the title describes, some of the buttons on each question component do not have the correct inputType in their ariaLabel field. This will affect; MCQ, GMCQ, text, slider, matching.

**Comment by oliverfoster** [comment]
Is this supported in NVDA JAWS and VoiceOver?

**Comment by brian-learningpool** [comment]
The `inputType` attribute only dictates what type of control the authoring tool uses to render the editing field.  Right now there's an inconsistency in that the placeholder for `buttonText` label can be pulled through from the global course defaults, but the `ariaLabel` cannot, because it's set to a simple string.

**Comment by oliverfoster** [comment]
+1

**Comment by oliverfoster** [comment]
yea, my fault
