### ISSUE TITLE
adapt-contrib-pageLevelProgress incorrectly calculating the components

### ISSUE THREAD

**Issue by ryan-lynch** [adaptlearning/adapt_framework#1138]
The behaviour of the page level progress extension doesn't seem quite right.

I created a simple course with 3 MCQ components in it. After one completion the bar progresses only 20% and is 40% across with one component left to complete. It then jumps to 100% on completion of the third and final component. 

I would expect this to progress 33% for each component?

**Comment by oliverfoster** [comment]
This is a long and winding story.

Because PLP and _isComplete are independent calculations, we had a horrid problem that stemmed from having, for example, 5 components listed in the PLP on a 10 component page. 

This works well if the items in the PLP included the last item on the page. In many instances this wasn't the case and so the PLP would show as 100% but the page wouldn't be completed (as the user hadn't visited the last component) and the course wouldn't be completed. 

To highlight the issue I introduced and extra point for the page completion. So for your 3 MCQs it'd be 3 points for each MCQ/PLP entry and 1 point for the page completion.

The is a property call _showPageCompletion for the PLP which turns off this behaviour.

**Comment by ryan-lynch** [comment]
Hi Ollie,

I thought there may be an explanation for this issue. However, when I was investigating I noticed that if _showPageCompletion is turned off then the calculateCompletion() code adds 1 to nonAssessmentTotal and also adds 1 to assessmentTotal which is essentially giving the 'page' two extra points. I don't think there is any need for _showPageCompletion property to add 1 to assessmentTotal but I could be wrong?

Have a look at my PR here and feel free to correct me on this:  https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/pull/87

Thanks

**Comment by oliverfoster** [comment]
Yea, that sounds about right.

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/commit/3f001e524ed9efb0a99c5e753879f355d8b47d2a
