### ISSUE TITLE
adapt-contrib-spoor: Old code?

### ISSUE THREAD

**Issue by webb-nickj** [adaptlearning/adapt_framework#1203]
In adapt-stateful-session.js, lines 81-85 include possibly old code with unused event listeners.

```Javascript
    this.listenTo(Adapt.blocks, 'change:_isComplete', this.onBlockComplete);
    this.listenTo(Adapt.course, 'change:_isComplete', this.onCompletion);
    this.listenTo(Adapt, 'assessment:complete', this.onAssessmentComplete);
    this.listenTo(Adapt, 'questionView:complete', this.onQuestionComplete);
    this.listenTo(Adapt, 'questionView:reset', this.onQuestionReset);
```

The questionView:complete event handler doesn't ever seem to get called.

https://github.com/adaptlearning/adapt-contrib-spoor/blob/master/js/adapt-stateful-session.js#L88-L89

**Comment by moloko** [comment]
> The questionView:complete event handler doesn't ever seem to get called.

I concur. I can also see no evidence of `questionView:reset` being called. And there seems to be no reference to either of these two events in any of the rest of the code.

I guess this also means that `_sessionID` and `assignSessionId` are both now redundant as well since the only place the `_sessionID` was used was in `onQuestionReset`.

**Comment by oliverfoster** [comment]
Weird innit. Might check the blame, etc etc but for the moment we can consider this stuff unnecessary.

**Comment by moloko** [comment]
redundant code removed in https://github.com/adaptlearning/adapt-contrib-spoor/commit/ece293d0310c8889c6790924c1866c61037840e4
