### ISSUE TITLE
setOptional on children?

### ISSUE THREAD

**Issue by chris-steele** [adaptlearning/adapt_framework#1221]
https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/models/adaptModel.js#L39

Should this not be a call to setOnChildren?

**Comment by oliverfoster** [comment]
Looks like it.

**Comment by oliverfoster** [comment]
I removed that behaviour from adaptModel because it used to override the completion calculations on blocks. I think it would be better if we did it the other way round and had an "isOptional" function on the models which searches parents? Cascading properties are a bit problematic occasionally. All those cascading, synchronous operations.

**Comment by moloko** [comment]
@chris-steele can this be closed now?

**Comment by chris-steele** [comment]
@moloko yep, thanks.
