### ISSUE TITLE
add dir-rtl | dir-ltr class to html element

### ISSUE THREAD

**Issue by lc-thomasberger** [adaptlearning/adapt_framework#1269]
These classes are required to properly style the content when switching from ltr to rtl and back again

**Comment by tomgreenfield** [comment]
Hi @lc-thomasberger, I was under the impression that the `dir-rtl` class is already handled in https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/models/configModel.js#L31 and https://github.com/adaptlearning/adapt_framework/blob/feature/ml/src/core/js/app.js#L186? A `dir-ltr` class in theory wouldn't contain any styles since all default styling is respective to left-to-right.

**Comment by lc-thomasberger** [comment]
@tomgreenfield when you go from rtl > ltr direction keeps set as "rtl". Adding dir-ltr to the html element forces this to the right direction for the whole document.

Please see also: https://github.com/adaptlearning/adapt_framework/issues/1277
This can be fixed by re-rendering Drawer and applying the dir-xxx classes to html.
