### ISSUE TITLE
Accessibility & Fonts

### ISSUE THREAD

**Issue by mldaq** [adaptlearning/adapt_framework#1272]
The accessibility folks here at SAP took a look at a course I built and had some questions on how the Adapt env was handling fonts - more specifically sizing. They suggested using em instead of pt  sizing - this way you could set the base or body font to the users system font size as a starting point. So, 1em would be the body font size and everything would be adjusted from there. Therefore, always meeting the needs from a font perspective of the end-user (making it more accessible). 

I made an attempt to do this in my theme, but as you know it creates a snowball effect. It would be nice to see this update in the vanilla theme.

Thanks,
Mark

**Comment by chucklorenz** [comment]
+1
I suspect that converting Vanilla to pixels might be a daunting undertaking, but it would be so good for accessibility. Because the theme is a plug-in, Vanilla's units can always remain in pixels. Producing an alternative that employs ems wold be possible as long as any Less being moved into core uses them instead of pixels. Is this something we can consider @oliverfoster @guywillis ? Perhaps such a theme might also strive to be a high-contrast alternative.

**Comment by tomgreenfield** [comment]
Could also consider using [rem](https://snook.ca/archives/html_and_css/font-size-with-rem).

**Comment by andrewhosgood** [comment]
@tomgreenfield rem gives no love for IE8: http://caniuse.com/#feat=rem

Don't know if that's important going forward. Even then, IE9 and 10 support is patchy... :(

**Comment by oliverfoster** [comment]
No that we don't have ie8, ie9 and ie10. This is going into the theme refactor being run out of the Kineo front end developer group.

**Comment by oliverfoster** [comment]
Removed from accessibility epic as being done in theme refactor.

**Comment by oliverfoster** [comment]
closing as it is included in the v5 work stream and is currently being implemented
