### ISSUE TITLE
Language selector: Icon

### ISSUE THREAD

**Issue by kineotesting** [adaptlearning/adapt_framework#1275]
![1](https://cloud.githubusercontent.com/assets/19309048/19231066/db8d571c-8ecf-11e6-91fb-a6abd2525f26.jpg)

This icon that represents the language selector in-course--is it universally recognisable? Because it means nothing to me, so from a usability standpoint it might be something to look at.

**Comment by moloko** [comment]
I'm not sure there _is_ a universally recognisable icon for this. The one we've used is relatively well known I think, for example you can see it used in MS-Office (though as the 'translate' button rather than the 'language' button):
![outlook](https://cloud.githubusercontent.com/assets/1249597/19234539/304cefe2-8ee4-11e6-968f-98fcc35f7299.png)

This is, of course, just the default icon. Course developers can set their own icon in the theme.

We could look to make a few more options available perhaps.

**Comment by lc-thomasberger** [comment]
Agree with Matt, developers would most likely customize the languagePicker-View and update the theme to meet their requirements.

Possible alternatives for the existing icon:
http://fontawesome.io/icon/language/
http://fontawesome.io/icon/globe/

We might add a _navigationIconClass attribute to the languagePicker config that applies a custom class to the icon in the navigation bar.

**Comment by moloko** [comment]
I quite like [this one](http://fontawesome.io/icon/language/) - maybe we should hold a vote on the forums for what the default should be?

**Comment by lc-thomasberger** [comment]
PR's:
https://github.com/adaptlearning/adapt-contrib-vanilla/pull/198
https://github.com/adaptlearning/adapt-contrib-languagePicker/pull/22

**Comment by tomgreenfield** [comment]
This will also need adding to [core](https://github.com/adaptlearning/adapt_framework/tree/master/src/core/fonts).

**Comment by kineotesting** [comment]
Confirmed fixed.
