### ISSUE TITLE
adapt-contrib-assessment: Restoration of assessment loses presentation components

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#1323]
When an assessment also includes a mix of presentation components (graphic, text, etc.) and an assessment has multiple attempts, if you re-attempt the presentation components are not rendered.

I have a feeling this is certainly due to the serialisation to persist the assessment between attempts, but it would be useful to making it more robust, e.g. if banks and randomisation are off, then presentation components are re-rendered.

This was raised by @webb-nickj on the Gitter rooms.

**Comment by chris-steele** [comment]
@brian-learningpool It does warn in the README "Blocks inside an assessment article must contain a question. Any blocks containing only presentation components will not be rendered when the article is restored." but I do agree that this change is worth doing. Perhaps we should edit the above entry in the README to state "should" rather than "must" now?
