### ISSUE TITLE
Consider moving to BrowserSync

### ISSUE THREAD

**Issue by andrewhosgood** [adaptlearning/adapt_framework#1364]
Using something like https://browsersync.io/ would mean we wouldn't have to run two terminal windows; one for `grunt dev` and another for `grunt server` when building a course.

It also supports things like CSS injection where when a change in the source files occurs, it gets built and updated in the browser without having to refresh. There are also a load of options supporting simultaneous scrolling across devices etc. that make theme development in particular a load easier.

**Comment by oliverfoster** [comment]
i did build a version of it for adapt a while ago, using gulp + browsersync instead of grunt. the thing i didn't like about it is that the browsersync package is huge and has to be compiled for each system. this compilation requirement means you can't pick up a build with the node_modules folder from windows > unix or vice-versa without having to reinstall node_modules, and it's huge - if i'm honest, it all got rather tedious.

**Comment by oliverfoster** [comment]
i suggest we move away from grunt/gulp/etc and go for webpack or something similar which has an entire development environment ethos built right in.

**Comment by andrewhosgood** [comment]
I suppose it is quite large. Is there not a way to make an "Adapt tools" package which installs all of these Node modules globally? That might make for quicker installing, although I suppose I can see issues with different versions of modules...

It was just a thought. Webpack would be a step forward though :)

**Comment by moloko** [comment]
added look at webpack to #835
