### ISSUE TITLE
adapt-contrib-spoor: Score always submitted to LMS as percentage

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#1386]
The Spoor extension sends back the score as as a percentage to the LMS, regardless of whether the Assessment has `_isPercentageBased` set to `false`.

https://github.com/adaptlearning/adapt-contrib-spoor/blob/master/js/adapt-stateful-session.js#L116

**Comment by oliverfoster** [comment]
SCORM 1.2?

**Comment by oliverfoster** [comment]
![image](https://cloud.githubusercontent.com/assets/7974663/22158163/e3d6e24a-df32-11e6-8562-02d9bcacde6e.png)

**Comment by kevindoherty30** [comment]
Within Moodle, you can normally set the score to be non-percentage based, reflecting the set up within a module. 

This is done by changing the highest grade within the grading settings of a SCORM activity. I've tried this with an adapt module and this is where we see it always reporting out a percentage based score regardless of the settings in the article settings and project settings.

Could this be an issue because the assessment extension doesn't update the imsmanifest masteryscore and this is bypassed for the scores in the article.json and course.json?

**Comment by moloko** [comment]
even though, as @oliverfoster points out, the score must be a value between 0 and 100, there's nothing that says it has to be a percentage score, that's just the most common use-case by far.

if we were to amend the assessment extension to allow for the 'raw score' to be sent then we would obviously need to consider what to do in the event that the raw score is > 100

**Comment by oliverfoster** [comment]
does it have it be an integer?

**Comment by moloko** [comment]
> does it have to be an integer

No, the datatype is listed as CMIDecimal which is defined as "A number that may have a decimal point.  If not preceded by a minus sign, the number is presumed to be positive.  Examples are "2","2.2" and “-2.2). "

**Comment by brian-learningpool** [comment]
I think there might be an associated issue with the Assessment extension on this line too:
https://github.com/adaptlearning/adapt-contrib-assessment/blob/master/js/assessment.js#L297

**Comment by brian-learningpool** [comment]
PR here:
https://github.com/adaptlearning/adapt-contrib-spoor/pull/150

**Comment by brian-learningpool** [comment]
PR merged, closing issue.
