### ISSUE TITLE
Expose a starting volume on the Media component

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#1410]
This would be a very useful feature, especially for linking YouTube videos which are beyond the user's control.

**Comment by barryo-learningpool** [comment]
I've got this working with a new setting called "Default Volume" which has a dropdown with volume percentages from 0% to 100% in 10% increments (as @brian-learningpool) suggested.

Would it be ok to throw in a "Show Volume Control" setting as well? Otherwise the only option for the user to change the volume is by using the up/down arrow keys.  Of course this could also be controlled by pasting in an object into the "Player Options" setting but I suspect not all users would be able to do that

**Comment by oliverfoster** [comment]
This won't work on mobile where the devices where volume can only be 0 or 1.

**Comment by barryo-learningpool** [comment]
Thanks @oliverfoster. Does that mean we shouldn't try to show the volume control or try to set a specific volume level between 0 and 1?  It looks like the volume control just doesn't show up on ios devices as the audio level is under the user's physical control.

**Comment by oliverfoster** [comment]
I'm not sure. If it's needed on desktop it would be nice to have... I guess?
It just needs to be made clear that it won't work on ios. Android needs testing.

**Comment by barryo-learningpool** [comment]
I guess its fair enough to add something like "Not supported in iOS devices" with further explanation of what will happen in the help text

**Comment by oliverfoster** [comment]
Yup. That sounds sensible.

**Comment by barryo-learningpool** [comment]
Ok I'll add that in.  We tried https://www.w3schools.com/html/html5_video.asp on an Android device and the volume control shows up but it just allows the user to mute/unmute the audio.

**Comment by oliverfoster** [comment]
Cool. I think it's probably safe to say that volume isn't available on mobile and show the volume controls on mobile at all?

**Comment by barryo-learningpool** [comment]
Here is the PR: https://github.com/adaptlearning/adapt-contrib-media/pull/167

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt-contrib-media/commit/80db0f08193d465ae8ad91d8b24996529fd37540
