### ISSUE TITLE
add _assessment._requireAssessmentPassed to course.json

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1446]
This is a very useful setting; it should be in the OOTB course content.

**Comment by tomgreenfield** [comment]
Would be good to get consensus on this considering the reservations about this setting outlined in https://github.com/adaptlearning/adapt_framework/issues/1328.

**Comment by oliverfoster** [comment]
Turns out it's just a tracking criteria thing. The plp vs completion representation (assessment + page) issue needs a decent design solution.
The assessment is an abstract to the content. If we could stop the article becoming complete until the articleAssessment is done, that would mean we can take all the subProgress stuff out of PLP.
