### ISSUE TITLE
graphic - make optional/not included in PLP as standard?

### ISSUE THREAD

**Issue by hmaffin** [adaptlearning/adapt_framework#1466]
I find myself always turning graphics off in PLP or making them optional - can we make this the default for this component somehow?

**Comment by moloko** [comment]
hi @hmaffin this one's a bit tricky as `_isOptional` is a core property and so the settings for it are not listed in the plugin's properties.schema. 

Default for plugins like PLP can't be specified by component type. However, there is an argument to be made for changing the default value of PLP's `_isEnabled` property at the component level so that instead of having to go and set which components should be excluded from PLP you have to set which are included instead. If you can persuade the community that is preferable we can change it.

There is a wider question around being able to create user/project defaults which is addressed by AT ticket [#1505](https://github.com/adaptlearning/adapt_authoring/issues/1505)
