### ISSUE TITLE
Extend tutor

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1469]
Pull in some other tutor types to expand the extension offering

types:
* ```notify``` default, notify popup
* ```overlay``` sits over the component
* ```inline``` sits after the component

example json:
```json
"_tutor": {
    "_type": "inline"
},
"_feedback": {
    "correct": "Correct text",
    "incorrect": "Incorrect text"
}
```

**Comment by oliverfoster** [comment]
I'm open for suggestions on how to improve this.

**Comment by amruta-thakur** [comment]
Hi @oliverfoster -
Below are the 4 bullet suggestions or questions on above comment:
- Can we give this changeable titles in "_feedback" object? Such as:
```
"_feedback":{
    "correct": "Correct text",
    "incorrect": "Incorrect text",
    "buttonTitle": "Continue"
}
```

-  What do this means feedback you can't dismiss? Does the feedback is always visible? Or is it like you have suggested in inline feedback?

- Graphics, video can also be added in "_feedback" object. This one I have already done in my local framework,
For Example:
```
"_feedback":{
    "correct": "Correct text",
    "incorrect": "Incorrect text",
    "buttonTitle": "Continue",
    "graphics": {
         "src":"course/en/images/small.jpg", // This will include path for any image,file, or video
         "alt":"no image"
   }
}
```

- Moving feedback text to the tutor means we have to move all the functionality for feedback in questionView to the tutor. In this case I would suggest we will just trigger the custom event from questionView as soon as answer have been submitted and tutor will listen to this event and all the checking for correct, incorrect and partly correct answer will be done in tutor and will send the appropriate feedback to the notify as well. This is just my opinion, may be we have to make more huddle for the same because we need to change functionality in core.
