### ISSUE TITLE
adapt-contrib-trickle: _isLockedOnRevisit

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt_framework#1481]
Doesn't look like models with `_isLockedOnRevisit: true` do actually re-lock.

**Comment by oliverfoster** [comment]
This is as the behaviour doesn't match the variable name.

* https://github.com/adaptlearning/adapt-contrib-trickle/blob/master/js/handlers/completion.js#L68
Because trickle unlocks on completion it is tied into the completion attribute. If a component is not either ``hard`` or ``soft`` reset, and ``_isCompletionRequired`` then trickle will not re-lock.

* https://github.com/adaptlearning/adapt-contrib-trickle/blob/master/js/handlers/buttonView.js#L185
If trickle has a button and is waiting on it and is completed, then a re-lock can be applied.
