### ISSUE TITLE
adapt-contrib-spoor: "_requireCourseCompleted": true, "_requireAssessmentPassed": true

### ISSUE THREAD

**Issue by danielghost** [adaptlearning/adapt_framework#1557]
If completion is set to be based on both an assessment being passed and the mandatory content being completed, it is possible to have previously passed the assessment and then subsequently fail it at some point before the rest of the content was completed. This would leave the lesson_status as incomplete.

Even if the assessment used a soft reset to maintain completion, the failed status for your last attempt overrides the fact that you have at some point passed and looked at all the content. If the assessment isn't using a hard reset should `_isAssessmentPassed` change from true to false in this situation?

**Comment by moloko** [comment]
> the failed status for your last attempt overrides the fact that you have at some point passed and looked at all the content

I would argue that this isn't necessarily wrong... after all the setting is called `_requireAssessmentPassed` and not `_requireAssessmentPassedAtLeastOnce` ;-)

Wouldn't the simple solution be to enable `_shouldStoreResponses` so that once the assessment is passed it doesn't reset if you go back into it? Or is it that you have a requirement for the user to be able to retake the assessment so as to have the option to improve on their previous score?

**Comment by danielghost** [comment]
As you say, there are a few ways around this and I wasn't looking to find a solution for a specifc course, I just happened to notice that this was possible under certain configurations and wondered if it should ever be possible.
