### ISSUE TITLE
navigation max-width margin:auto issue

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#1579]
navigation bar needs it's own wrapper as it has been moved outside of the #wrapper div

**Comment by prajaktakitukale** [comment]
Currently navigation and wrapper start from the same position i.e from the top 
Thinking forward, what expected is wrapper should always start from the end of navigation, do we need padding-top to the wrapper ? 
Also can you please elaborate the above issue ?

**Comment by oliverfoster** [comment]
We usually have padding-top on the navigation:
https://github.com/adaptlearning/adapt-contrib-vanilla/blob/master/less/src/wrapper.less#L8

**Comment by oliverfoster** [comment]
specifically an issue in ie8

**Comment by oliverfoster** [comment]
![image](https://user-images.githubusercontent.com/7974663/27921019-5e47677a-626e-11e7-858f-858783ae14d6.png)

**Comment by guywillis** [comment]
IE8 issue can be fixed in two ways depending on what solution you're after.

The first fix centres the navigation bar so the left and right edge line up with the content edges.

`
left: 0;
right: 0;
`

The second fix mimics the display of the navigation bar in modern browsers (where it spans the entire width of the screen). To proceed with this solution, remove the max width attached to the navigation bar in the LESS.
