### ISSUE TITLE
adapt-contrib-trickle buttons visible when they shouldn't be

### ISSUE THREAD

**Issue by chris-steele** [adaptlearning/adapt_framework#1692]
Appearing in 403337 - pernicious bug with trickle buttons layering up on top of each other.

### Steps to replicate
1. setup trickle at article level for two or more articles
2. use `_styleBeforeCompletion:visible` and `_onChildren:false` - everything else as default
3. place a question in second article (for example) as last child
4. complete first article
5. return to menu then back to page
6. complete second article, completing question setup in (3) last
7. after closing the question feedback the trickle button for the first article appears overlaid with the trickle button for the second article

### Explanation

`buttonView::onUnoverlay` invoked when feedback is closed, results in call to `checkButtonAutoHide` on all `buttonView` instances.

### Solution

Modify `checkButtonAutoHide` to check `isStepLocking` property; if `false` ensure trickle button is hidden:

```javascript
if (!this.allowVisible || !this.isStepLocking) {
    this.setButtonVisible(false);
    return;
}
```

I think there may need to be an additional check on the value of `_styleAfterClick`: if not `hidden` then we should not hide the button I presume?

**Comment by chris-steele** [comment]
@oliverfoster could do with the creator's eyes on this one if you have time...

**Comment by chucklorenz** [comment]
Chris's solution code helped me today. In my case I had a trickle button that continued to appear at the end of the course, but only upon returning to the unfinished course. (We were testing Bookmarking.) I could tell it was the trickle button from the first block because its "text" property was different from the other blocks. Trickle was set on blocks, not articles. Was using  _styleBeforeCompletion:visible. I modified checkButtonAutoHide as above. The errant trickle button no longer appears. 

Admittedly, I don't know how to relate these two situations. But the code apparently helped.

**Comment by moloko** [comment]
this issue is very old, is it still relevant?

**Comment by chris-steele** [comment]
@moloko I'll go through the steps to replicate again when I have some time to check, though I noticed the logic at https://github.com/adaptlearning/adapt-contrib-trickle/blob/master/js/handlers/buttonView.js#L166 and https://github.com/adaptlearning/adapt-contrib-trickle/blob/master/js/handlers/buttonView.js#L171 seems to be inverted - I've asked @tomgreenfield what his take on this is. Will post back when I have more info.

**Comment by moloko** [comment]
closing due to age & lack of activity
