### ISSUE TITLE
Remaining attempts text is not accessible.

### ISSUE THREAD

**Issue by ryan-lynch** [adaptlearning/adapt_framework#1709]
There is currently no accessibility for "remaining attempts" on components. 

I have two potential solutions: 

1. add an aria-label attribute via JS in core buttonsView 
2. add a tabindex attribute to the template in core and the vanilla theme. 

I would probably prefer to add a concrete aria-label via JS.

**Comment by moloko** [comment]
as discussed I think the way forward here is to amend the final few lines of `updateAttemptsCount` in buttonsView.js from this:
```js
if (shouldDisplayAttempts) {
    this.$('.buttons-display-inner').html(attemptsString);
}
```
to this:
```js
if (shouldDisplayAttempts) {
    this.$('.buttons-display-inner').html(attemptsString).a11y_text();
}
```

**Comment by danielstorey** [comment]
I can foresee this kind of behaviour being needed more and more. Would it be worth creating another helper or even allowing an optional argument [here](https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/libraries/jquery.a11y.js#L956-L965) which when present inserts accessible text rather than converting the existing content.

**Comment by oliverfoster** [comment]
fine plan! i'll +1 if you pr.

just as a note.... 
```javascript
this.$('.buttons-display-inner').html($.a11y_text(attemptsString));
```
also does the same thing

**Comment by danielstorey** [comment]
Of course, but less brackets is always good ;) #1725

**Comment by oliverfoster** [comment]
couldn't agree more

**Comment by moloko** [comment]
done in https://github.com/adaptlearning/adapt_framework/commit/9d50f2fc9b71be7b6294decfa05d9aba3e9b6759
