### ISSUE TITLE
Allow template that notify uses to be specified

### ISSUE THREAD

**Issue by chris-steele** [adaptlearning/adapt_framework#1840]
issue https://github.com/adaptlearning/adapt_framework/issues/1525

This will allow notify to be more flexible in what it can display and perhaps reduce the reliance on custom overlay/lightbox plugins.

**Comment by oliverfoster** [comment]
Could you turn this into accepting a view rather than a template?

Allowing a template override only means that the view behaviour associated with the template must be external to the notify and must seek the DOM node after render of the notify and before use interaction. If the view is instantiated and handed off to the notify it makes for a much cleaner API.
I would prefer if this behaved more like the drawer; in that it should accept child views. I would see this as a leapfrog step, scrapping the transition to bespoke templates and allowing bespoke, atomized behaviour, templates and styling.

**Comment by oliverfoster** [comment]
@chris-steele is there an open pr for this?
