### ISSUE TITLE
Incorrect course data is loaded when language picker is used

### ISSUE THREAD

**Issue by RobertPeek** [adaptlearning/adapt_framework#1916]
### Subject of the issue
When creating a multi-language course the course seems to load data for all languages.

### Your environment
* Framework version 2.2.3
* IE11
* Windows 7

### Steps to reproduce
- Download and install the latest version of the framework (2.2.3)
- Duplicate the course/en folder and rename to 'de' for German.
- Enable language picker in config.json
- Add more resource items to the German course.json.
- Build and preview course.
- Choose the English version on the language picker.
- Open course resources.

### Expected behaviour
Drawer should only show current language resources.

### Actual behaviour
Resources for English course and German course are displayed in the Drawer.

**Comment by moloko** [comment]
Confirming I can replicate this. 

It's very odd, what seems to be happening is the grunt task that copies the JSON from src to build is getting a bit muddled and seems to be copying src/course/de/course.json into build/course/en/

It's difficult to check for sure as once I'd edited src/course/en/course.json just to see what that did it all started working perfectly again and now I can't replicate it. So maybe it's something to do with the timestamps on the files??

Also just to note that initially the course wouldn't load at all due to an error originating from helper.js, I'd already [logged](https://github.com/adaptlearning/adapt_framework/issues/1908) and [fixed](https://github.com/adaptlearning/adapt-contrib-languagePicker/pull/30) this but had forgotten to release a new version of the languagePicker plugin... I'll do that shortly!

**Comment by RobertPeek** [comment]
Thanks for the quick reply @moloko 

It is very odd indeed. I have added the Glossary extension now and even after editing both course.json files the error still occurs and this time with glossary terms showing for German in the English.

I'm not sure the entire wrong json is being compiled into the build folders as from the screenshot below you can see that I had changed the Display Title for the German course and this does display correctly.

![image](https://user-images.githubusercontent.com/7251995/34877823-825b6c58-f79f-11e7-82df-41fe8e78341b.png)

And the English version does display the correct Display Title but with the extra German glossary items

![image](https://user-images.githubusercontent.com/7251995/34877886-c517b344-f79f-11e7-9877-c147fe00e670.png)

**Comment by moloko** [comment]
I think you might be right on that... I had the same thought but was unable to check because it all just started working fine again.

Will have to defer to someone with more knowledge of the Grunt code...

**Comment by NayanKhedkar** [comment]
PR:https://github.com/adaptlearning/adapt_framework/pull/1920

**Comment by moloko** [comment]
thanks @NayanKhedkar ! @RobertPeek any chance you could test this out?

**Comment by RobertPeek** [comment]
Certainly can no problem

**Comment by RobertPeek** [comment]
That has fixed it @NayanKhedkar  and @moloko . The languages build as expected now, cheers!
