### ISSUE TITLE
assessment: uses _questionWeight rather than _score to calculate each question's score

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#1974]
Given that questions have a `setScore` function that's there specifically to allow them to calculate their score based on `_questionWeight`, it seems a little bit odd that the `_score` is then completely ignored by the assessment's scoring calculations.

In the example I'm working to I have a question component that presents the user with multiple questions - therefore I'd like the assessment to take into account that the user got, say, 3 out of a possible 5 correct - but at the moment I can't see that this is possible.

What is clear is that if this is changed to use `_score` instead of `_questionWeight` it will be necessary to make some adjustments to matching and textInput since they currently calculate their score based on the number of correct answers given - so to maintain existing behaviour for these it will be necessary to do something like add a setting (defaulted to `true`) that says that a score should only be given for a completely correct answer.

**Comment by moloko** [comment]
Actually I might be wrong about that last paragraph since assessment only checks the score if the question was answered correctly... but maybe it should check it regardless so as to allow for partially-correct questions to be counted if needed? That's a separate issue though ;-)

**Comment by oliverfoster** [comment]
At the moment `_questionWeight`  is behaving as a `_maxScore` to which the sum of the question answers is proportionally readjusted for the `_score` and from where the assessment can calculate a percentage completion. 
The only reason to take `_score` (ignoring `_isCorrect`) instead of `_maxScore` when `_isCorrect` is to get a partial correctness. 
The trouble is, as far as you explained it to me before, is that it is entirely possible then to pass an assessment without having answered any question correctly.
It sounds like an assessment boolean? `_allowPartialCorrectness`

**Comment by moloko** [comment]
> It sounds like an assessment boolean? `_allowPartialCorrectness`

Yes, or something more like `_canShowMarking` that can be set either at question level or at assessment level

**Comment by oliverfoster** [comment]
Ooo yea, that's a nice idea.

**Comment by brian-learningpool** [comment]
Hi @oliverfoster, @moloko actually pointed me in the direction of this ticket when I stumbled across the very same issue.

I think real issue here is that `_questionWeight` isn't actually behaving like a weighting at all -- as you've said it's more like a maximum score.  

If `_score` properties on questions were to permit a value between 0 and 1 I think that would cover scenarios where we want to get into partial scoring.  If the `_questionWeight` were then used as a multiplier to calculate the value of the question in relation to the others in the question I think that would work.

(The scenario that led me to notice this issue was a requirement to have a `_score` defined on a component that's linked to the number of attempts on the question, i.e. all correct on the first attempt gets 100% (or 1), all correct on the second gets 50% (or 0.5).

**Comment by oliverfoster** [comment]
Where I get unstuck is with the impact of these changes on a final assessment (I understand that there are different end use-cases to take into account and not all question components will finish in a final, assessment as it is at the moment).

#### Points of concern
* Visually, all questions are binary in their correctness.
* To derive percentages we will always need to know what the total maximum scores are.

### Currently
#### Values and calculations
* `float _score` range between 0-1.
* `integer _maxScore = 1`
* `float _questionWeight` is any positive value
* `boolean _isCorrect = (_score === _maxScore)`
* `float _weightedScore = _questionWeight * _score`
* `float _maxWeightedScore = _questionWeight * _maxScore`

#### Assessment correctness
The assessment doesn't currently count incorrect components in the total score, so there was no need to count the `_weightedScore` value, only either `_maxWeightedScore` or 0 depending on the question's correctness.

* `_correctedWeightedScore = _isCorrect ? _maxWeightedScore : 0` 
* `_totalWeightedScore` sum of `_correctedWeightedScore`
* `_totalMaxWeightedScore` sum of `_maxWeightedScore`
* `_percentageCorrect = (100 / _totalMaxWeightedScore) * _totalWeightedScore`

#### Confusing bits
* `float _maxWeightedScore = _questionWeight * _maxScore`
* `float _weightedScore = _questionWeight * _score`

 `_maxWeightedScore = _questionWeight` as it is always multiplied by 1, `_maxScore`. Because of this the assessment uses `_questionWeight` in place of `_maxWeightedScore` throughout.
Because `_weightedScore` is never used due to the correctness check, you won't see it in any calculations.

The outcome is:
* `_correctedWeightedScore = _isCorrect ? _questionWeight : 0` 
* `_totalWeightedScore` sum of `_correctedWeightedScore`
* `_totalMaxWeightedScore` sum of `_maxWeightedScore`
* `_percentageCorrect = (100 / _totalMaxWeightedScore) * _totalWeightedScore`

### Matt's Proposal
#### Values and calculations
* `float _score` any positive up to `numberOfOptions`.
* `integer _maxScore = numberOfOptions`
* `float _questionWeight` is any positive value
* `boolean _isCorrect = (_score === _maxScore)`
* `float _weightedScore = _questionWeight * _score`
* `float _maxWeightedScore = _questionWeight * _maxScore`

#### Assessment correctness
It doesn't seem like you'd want to describe the assessment correctness in the usual way with this use-case. But it would be derived from `_score` with no correctness or weight taken into account.

* `_totalScore` is the sum of `_score`
* `_totalMaxScore` is the sum of `_maxScore `
* `_percentageCorrect = (100 / _totalMaxScore) * _totalScore`

### Brian's Proposal
#### Values and calculations
* `float _score` range between 0-1
* `integer _maxScore = 1`
* `float _questionWeight` is any positive value
* `boolean _isCorrect = (_score === _maxScore)`
* `float _weightedScore = _questionWeight * _score`
* `float _maxWeightedScore = _questionWeight * _maxScore`

#### Assessment correctness
This would be derived from `_weightedScore` with no correctness taken into account.

* `_totalWeightedScore` is the sum of `_weightedScore`
* `_totalMaxWeightedScore` is the sum of `_maxWeightedScore`
* `_percentageCorrect = (100 / _totalMaxWeightedScore) * _totalWeightedScore`

### Issues
#### Correctness
Because of the lack of correctness checks, it would be possible, using a sufficiently low `_scoreToPass` value, for an assessment to be passed without answering a single question correctly. This is as the sum of the incorrect answers could tip over the `_scoreToPass` threshold. We'd have to include a correctness check / option somewhere, but I think that's probably a good idea to allow both styles of calculation, one where correctness is taken into account and the other where not. We'd also have to assume that `_scoreToPass` wouldn't be used in some cases.
#### Readjusted weightings
In Brian's example where we readjust the `_questionWeight` according to the question answer, this math gets a little more confusing. I'd assume we'd want to use the original `_questionWeight` to derive the `_maxWeightedScore` and an `_adjustedWeight` to calculate the actual weighted score?

#### Removing weightings or maximum scores
Removing weighting or derivable maximums from the calculation altogether is interesting. In Matt's example we'd need to list the `_maxScore` separately if we'd ever mix that options/totalOptions method with overall percentages and in doing so break the `_score` 0-1 range assumption that runs throughout.

### Derived suggestions
* Introduce `float _maxScore` to be set by the component to account for the number of correct objectives to be satisfied.
* Change `float _score` from range between 0-1 to any positive up to `_maxScore`, to be set by the component signalling the number of objectives which were correctly satisfied.
* Use and add calculated values of `_weightedScore` and `_maxWeightedScore`
* Allow `_maxWeightedStore` to be manually overridden, or calculated before changes to the `_questionWeight` on attempts
* Provide two options for calculating `_totalWeightedScore`, one with correctness checks, the other without

**Comment by oliverfoster** [comment]
`_questionWeight` to become `maxScore` for questions without item scoring
`maxScore` on questions with item scoring is the highest possible score
assessment to have correctness threshold called `correctToPass` to compliment `scoreToPass`
