### ISSUE TITLE
adapt-contrib-slider: New option to hide indicator markers

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#2011]
### Subject of the enhancement
It would be useful if the Slider had an option to prevent numbering on intervals.

### Your environment
Adapt Framework v2.2.5
Slider v2.1.6

### Steps to reproduce
Add a slider with a range 1 to 100.

### Expected behaviour
It should be possible to prevent displaying the interval

### Actual behaviour
The intervals are too close together to render the numbers.

### Screenshots 
<img width="851" alt="screen shot 2018-03-15 at 11 23 19" src="https://user-images.githubusercontent.com/1327471/37460380-fc5dcd74-2842-11e8-8a7c-5ee905517c16.png">

**Comment by moloko** [comment]
Is it worth having a quick review of some of the slider settings alongside this? 

Specifically I'm not sure that `_showScale: false` is very useful in its current incarnation:
![slider_showscale-false](https://user-images.githubusercontent.com/1249597/37464521-80c07ff0-2850-11e8-9518-720825a177d4.png)

**Comment by brian-learningpool** [comment]
Absolutely.

**Comment by moloko** [comment]
@nilslp yes I think so because even if you did still want to hide them to make it look like the screenshot above you could still do so by setting both `_showNumber` and `_showScaleIndicator` to `false`

I also wonder if the start and end bars should still be shown even when `_showScale` is `false` - just having a horizontal line looks very odd to me, I'm struggling to see why that would be useful to anyone! So if you have `labelStart` and `labelEnd` defined, `showScale` set to `false` and everything else set to `true` you'd get this:
![slider_show_scale_proposal](https://user-images.githubusercontent.com/1249597/38880501-cb468bf6-425d-11e8-9f24-257a403a0f9e.png)

@brian-learningpool 's requirements could be met by introducing a new setting: `_showScaleNumbers`
