### ISSUE TITLE
Using accessibility, the focus does not go to correct answer button on attempting MCQ

### ISSUE THREAD

**Issue by chetan-hajare** [adaptlearning/adapt_framework#2056]
### Subject of the issue/enhancement/features
Using accessibility, the focus does not go to correct answer button on attempting MCQ as incorrect

### Steps to reproduce
Turn on the accessibility, go to MCQ and attempt wrong answer.
The focus goes to feedback popup. On closing the feedback popup, the focus goes back to feedback answer button.

### Expected behaviour
On closing the feedback popup, the focus should go back to correct answer button if the answer is wrong and the focus should go back to feedback answer button if the answer is correct since the submit button gets disabled. Also, on clicking the correct answer button, the focus should go to the correct/all options.

### Actual behaviour
On closing the feedback popup, the focus goes back to feedback answer button whether the answer is correct or wrong. The focus never goes to correct answer button.

**Comment by moloko** [comment]
hi @chetan-hajare this has come up a few times before but not for a while. the reason it doesn't do this is because we haven't yet found a nice way of explaining to a screen reader user what the correct answer is - so sending focus to this button would actually be quite a poor experience since. also see #911

**Comment by chetan-hajare** [comment]
I should have noticed that the issue has been already raised.
