### ISSUE TITLE
Unnecessary grunt process.

### ISSUE THREAD

**Issue by akshay-bhavsar** [adaptlearning/adapt_framework#2224]
### Subject of the issue/enhancement/features
Unnecessary grunt process.

### Steps to reproduce
Update any json file.

### Expected behaviour
grunt process should run once if only one file is changed.

### Actual behaviour
grunt process appears multiple times.

### Screenshots (if you can)
please find attached video which replicate the issue in grunt process

![issue-replicate](https://user-images.githubusercontent.com/26135970/45342668-44599200-b5bc-11e8-8c6d-829d25298425.gif)

**Comment by oliverfoster** [comment]
This is because the create-json-config is working on the src folder not the destination. Should be quite an easy fix.
https://github.com/adaptlearning/adapt_framework/blob/master/grunt/tasks/create-json-config.js#L13

**Comment by NayanKhedkar** [comment]
@oliverfoster I think above change need to be do with  [Line](https://github.com/adaptlearning/adapt_framework/blob/master/grunt/tasks/schema-defaults.js#L61).

**Comment by NayanKhedkar** [comment]
PR:https://github.com/adaptlearning/adapt_framework/pull/2227

**Comment by oliverfoster** [comment]
It is, definitely

**Comment by moloko** [comment]
Unfortunately #2227 isn't quite right as it's now writing course.json to the `build` folder instead of `build/course/{lang}`:
![course json](https://user-images.githubusercontent.com/1249597/46026382-207d6c80-c0e3-11e8-8ccc-031e73f1df43.png)

Which is having the knock-on effect of [stopping hot graphic popups from being displayed](https://community.adaptlearning.org/mod/forum/discuss.php?d=3496) (and probably other things too)

**Comment by brian-learningpool** [comment]
Perhaps that change should be reverted?

**Comment by NayanKhedkar** [comment]
Updated PR:https://github.com/adaptlearning/adapt_framework/pull/2230/

**Comment by akshay-bhavsar** [comment]
#Close
