### ISSUE TITLE
accessibility: Add correct +/ incorrect aria labels to ticks and crosses throughout.

### ISSUE THREAD

**Issue by oliverfoster** [adaptlearning/adapt_framework#2241]
### Subject of the issue
Secondary to [re-enabling the my / model answer behaviour](https://github.com/adaptlearning/adapt_framework/issues/2215), we need to add aria labels to the ticks and crosses in each component so that it's easier to read with the screen reader.

@moloko "Following a suggestion from a client on reviewing an accessible Adapt course, it was felt that this could be improved by allowing the 'correct/model answer' button to be made available to screen reader users, in combination with assigning descriptions for the ticks and cross images.
Naturally this is mainly focussing on MCQ/GCMQ and bit more thought will be needed for more questions like Slider, but it still sounds like a good suggestion."

**Comment by oliverfoster** [comment]
@swashbuck i've assigned this to you as you're doing some of the work already, i think this is specifically for adding correct / incorrect labels to the ticks and crosses on the mcq/gmcq/slider

**Comment by swashbuck** [comment]
@oliverfoster For a question that the user answers incorrectly, the following is read out:

- When clicking Show correct answer, "The correct answer was 1917"
- When clicking Show your answer, "Your answer was 1888"

Then, the marking icon next to the buttons reads "You answered incorrectly."

Finally, when tabbing back through the options, it reads something like "Correct, not selected, 1917"

> ...in combination with assigning descriptions for the ticks and cross images.

Since the aria text already indicates whether an answer was correct or incorrect, is there any value in labeling the actual tick/cross icons?  If so, was it suggested to label the icons like "cross icon" or simply "incorrect"?

**Comment by oliverfoster** [comment]
I'm inclined to agree there is little value in adding these as the questions already read out correct and incorrect.

**Comment by oliverfoster** [comment]
Perhaps do an audit of all the core plugins, write your conclusions and if necessary close this with "sufficient as is"?

**Comment by swashbuck** [comment]
Created issues and PRs:

- Matching: https://github.com/adaptlearning/adapt-contrib-matching/issues/154
- TextInput: https://github.com/adaptlearning/adapt-contrib-textInput/issues/116

I think Slider is fine as-is.  There are no correct/incorrect icons on the actual slider, and it reads the button marking icon properly.
