### ISSUE TITLE
page-level progress bar displayed in full width / larger

### ISSUE THREAD

**Issue by markusd1984** [adaptlearning/adapt_framework#2272]
I have seen more and more sites which use dynamic **full-width progress bars** (some switched to this from smaller to full width/larger ones) 

which makes it **visually more obvious** that there is a progress bar but more importantly to notice the progressed displayed and thus enhance the user experience feedback that progress is happening while progressing through the elements/page.

The bigger the more noticeable the impact of each individual progress but also the overall progress thus more **comforting and re-assuring** :) 

(besides the nudge plugin that may help but is rather pointy but could still be complementary to this)

**Comment by taylortom** [comment]
This isn't something that I'd expect to be implemented as part of the core theme/extension (largely because it's a matter of preference with relation to the styling), but there are a couple of ways you could implement this yourself:
- Theme amend: if you're looking to change the appearance of the existing page-level progress
- A custom extension: if you're looking to change how the progress bar _functions_, it would be advisable to create a new extension

**Comment by moloko** [comment]
Just to note that there's this plugin: https://github.com/gowithfloat/adapt-course-progress

And this one: https://github.com/kingsonline/adapt-contents

Some of the Learning Pool demo courses ([example](https://community.adaptlearning.org/learningpool_example2/index.html#/id/5614cd83e101c4b83f8b8803) have the PLP bar displaying across the top of the page in the way you describe. Not sure if this is something they've chosen not to release  publicly or I just can't find it ;-)

Also to note that [this proposed change](https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/pull/107) to pageLevelProgress will allow for progress bars to be displayed alongside each component's title.
