### ISSUE TITLE
slider: indicator not shown for model answer when either _showScale or _showScaleNumbers set to false

### ISSUE THREAD

**Issue by BillGilmoreLP** [adaptlearning/adapt_framework#2283]
### Subject of the issue/enhancement/features
When the slider is set to hide the numbers on the scale, and the user gets the answer wrong they don't get any feedback to show them the correct answer.

### Your environment
* Adapt Framework v3.2.1 & Adapt Framework v2.3.0
* Chrome

### Steps to reproduce
Set up a slider component.
set lowest value to 0.
set highest value to 10.
set answer to 5.
set Show scale to false.
Save and Preview.
Answer incorrectly.
Click 'Show correct answer'.

### Expected behaviour
The indicator should slide up to the correct answer and turn green to show the user what the correct answer should have been.

### Actual behaviour
The indicator disappears and the user does not know what the correct answer should have been.

### Video
https://www.useloom.com/share/d416d388d63c407795ce7e485ad1469a

**Comment by moloko** [comment]
in 'steps to reproduce' I think "set Show scale to false" should be "Set 'Show indicator numbers' (`_showScaleNumbers`) to false"?

**Comment by BillGilmoreLP** [comment]
I don't believe so:

Show number on indicator:
Controls whether the position number on the indicator should be shown or not
TRUE

Show position indicator:
Controls whether a position indicator on the scale should be shown or not
FALSE

Show scale:
Controls whether to show the lines and numbers of the scale or not
TRUE

**Comment by BillGilmoreLP** [comment]
Here is a video of my set up:
https://www.useloom.com/share/b9070c4ec5c6439faa6dc62f9f5140c3

**Comment by moloko** [comment]
hi @BillGilmoreLP sorry for the confusion but in the first video you posted the difference between the two slider instances appears to be that you have `_showScaleNumbers` ('Show indicator numbers' in the AAT) set to `false`. 

If I mimic that setup I get a similar issue in that the 'marker' above the scale shows for user answer:
![slider_showscaleindicator-false_user-answer](https://user-images.githubusercontent.com/1249597/48954366-14762580-ef41-11e8-8a8a-c0dc78c758c7.png)
But disappears when the model answer is shown:
![slider_showscaleindicator-false_model-answer](https://user-images.githubusercontent.com/1249597/48954378-2061e780-ef41-11e8-86c0-43311c2a2ece.png)

Which is definitely a bug as far as I'm concerned.

(I think perhaps there's an additional level of confusion in that your slider/theme has customised the `rangeslider__handle` so that it's got a circle containing either a tick or a cross - which looks really nice btw!) 

On the other hand, if I set `_showScaleNumbers` to `true` but set `_showScaleIndicator` ('Show position indicator' in the AAT) to `false` I get the _reverse_ behaviour in the the 'marker' is not present until the model answer is shown. **However**, I believe this was a deliberate decision as that's the only good way to show the 'model answer' when it's a 'range' of numbers:

![2018-11-23 17_07_08-adapt version 3 0 demonstration _ question components](https://user-images.githubusercontent.com/1249597/48954621-3e7c1780-ef42-11e8-860c-bf3cd56e2afc.png)

Does that makes sense? It's massively confusing with all the different settings which are all named slightly different in the AAT!

**Comment by moloko** [comment]
@BillGilmoreLP thanks for that, I think I've got it now: the same bug occurs if you set either/both of the following settings to `false`:
* _Show scale_ (`_showScale`)
* _Show indicator numbers_ (`_showScaleNumbers`)

[Your fix](https://github.com/adaptlearning/adapt-contrib-slider/pull/138) resolves the issue if just _Show scale_ (`_showScale`) or both are set to `false` but not if _Show indicator numbers_ (`_showScaleNumbers`) is.

**Comment by BillGilmoreLP** [comment]
Cool thanks for the update, i'll hopefully get onto his today. I've a few high priority tickets to sort first unfortunately. Cheers

**Comment by moloko** [comment]
Hey @BillGilmoreLP if I'm honest, I have no idea why that attribute is not present for you! I mainly use the Framework but if I check the component in a course published from the AAT, it's definitely present for me:
![at_slider](https://user-images.githubusercontent.com/1249597/49285034-4978ff80-f48e-11e8-8308-159569f2c9e5.png)

However, this is a good reminder that when coding adapt plugins it's important to take into account both FW and AAT in your code. 

In the FW, it's not necessary for the course author to specify every single setting in the JSON - in fact the vast majority are optional and so can be left out, with the code assuming sensible defaults (the README explains what these are and the `default` setting for the property in the schema should match)... so it's important you write your code with that in mind. You can see this in action in the `showScaleNumbers` function where it will only hide the numbers if `_showScaleNumbers` is set to `false` i.e. if `_showScaleNumbers` is not explicitly set in the JSON its value is assumed to be `true`.

Similarly it's important for someone who normally works in the FW to remember that the AAT will always include _every single property_ in the JSON, so it's important to code with that in mind

**Comment by BillGilmoreLP** [comment]
Hi @moloko 

Took me a while to get to the bottom of all these issues. I think this is a good fix for all the settings of the slider. What do you think?
https://github.com/BillGilmoreLP/adapt-contrib-slider/tree/issue/%232283

**Comment by moloko** [comment]
thanks for persisting with this; I'll try and give those changes a test tomorrow

**Comment by BillGilmoreLP** [comment]
no need to thank me sir, its wonderful to be a small part of this OS community 👍
