### ISSUE TITLE
adapt-contrib-textInput: unable to submit answer

### ISSUE THREAD

**Issue by SteveX** [adaptlearning/adapt_framework#2356]
### Subject of the issue/enhancement/features
> Uncaught TypeError: Cannot set property 'userAnswer' of undefined

### Your environment
Adapt authoring tool 0.6.3.
Adapt framework 4.0.1.
adapt-contrib-textInput 3.0.0

### Steps to reproduce
Click Submit button of a textInput

### Expected behaviour
Should work

### Actual behaviour
If there is just one part textInput I get this error when submitting:
> textInputModel.js:68 Uncaught TypeError: Cannot set property 'userAnswer' of undefined

If there are 2 parts there is no error, but it is marked incorrect even though it is correct
With 3 parts there is no error but it won't submit

**Comment by SteveX** [comment]
Oliver Foster suggested
```javascript
        onInputChanged:function(e) {
            var $input = $(e.target);
            this.model.setItemUserAnswer($input.parent('.component-item').index(), $input.val());
        }
```

**Comment by moloko** [comment]
Strangely I can't replicate the issue if I have only one input item - if I set it to have two or more then, like you, I cannot submit (it thinks I haven't given it enough answers) but I cannot seem to get it to trigger the error you're reporting or even figure out why it might trigger an error.

The problem I can definitely see (and which your PR addresses) is that it's trying to use the `index()` of the `<input>` element to figure out which item the answer belongs to - but since the `<input>` element is contained within a `<div>`, it'll always have an `index` of 0, so it thinks you're always supplying the answer to the first item only. But, if there's only one item, that shouldn't be a problem...
