### ISSUE TITLE
Rework grunt

### ISSUE THREAD

**Issue by danielstorey** [adaptlearning/adapt_framework#2414]
Add a 'courses' folder to the framework root.

Benefits:
- enable multiple builds using the same codebase, and eliminate the need for separate folders for each course
- separation of concerns - separate folders for content, code and output
- greater flexibility for the build API (#2396)

The build folder would probably need to change to 'builds' to accommodate multiple course output

**Comment by tomgreenfield** [comment]
Suggest https://github.com/adaptlearning/adapt_framework/issues/2363 should slip in first?

**Comment by danielstorey** [comment]
Yes, might need some harmony here. Maybe build/course is default but allow the option to specify alternate sources when working in the framework

**Comment by oliverfoster** [comment]
### Proposal

| variable | current behaviour | suggested behaviour | other |
| -- | -- | -- | -- | 
| sourcedir | code, JSON and course assets | code only | definable, `src/` (will become `node_modules/` later) |
| coursedir | n/a | source JSON and course assets only | definable, default is assumed to be in the `build/course` folder or `%outputdir%/course` |
| outputdir | When defined switches grunt behaviour to exclude `src/course` and specifies built output path. Predominantly used in AT builds.  | build output path | definable, `build/` |
| outputcoursedir | n /a | output JSON and course assets | definable, default is assumed to be in the `build/course` folder or `%outputdir%/course` |

All JSON+asset tasks should perform on the `%outputcoursedir%` only. Any other tasks which perform on the `src/course` folder should be removed.

#### To achieve the current behaviour with `src/course` to `build/course`
If `%coursedir%`and `%outputcoursedir%` are different, then a set of copy/watch tasks would be needed... and processing would continue on the `%outputcoursedir%`

### Advantages
* Allows us to have no `src/course` folder by default, reducing the duplication of course JSON and assets.
* Allows us to define a separate `src/course` style folder for manual course development if needed.
* Removes complex switching behaviour from the build process due to the current impact of `%outputdir%`.
* Segregates the code tasks from the JSON/course assets tasks.
