### ISSUE TITLE
adapt-contrib-hotgraphic: pin graphic causes duplication on resize

### ISSUE THREAD

**Issue by SteveX** [adaptlearning/adapt_framework#2435]
### Resize of browser causes duplication in DOM
When a hotgraphic item has a pin graphic and the browser window is resized, the component can be duplicated resulting in multiple copies of the hotgraphic in the page.

### Your environment
* Authoring tool 0.7.1
* Framework 4.0.1
* adapt-contrib-hotgraphic 4.2.0

### Steps to reproduce
Add a pin graphic (in the authoring tool), then preview. Drag the browser window until the mobile view is triggered, then wider again. The hotgraphic component is duplicated in the DOM. Resize several times and there will be multiple copies in the page.

**Comment by oliverfoster** [comment]
Does it happen on any browser resize or just when switching from small, medium and large layouts?

**Comment by moloko** [comment]
@SteveX believe this is now fixed in v5 of hotgraphic; alternatively you might want to look at [adapt-hotgrid](https://github.com/cgkineo/adapt-hotgrid/) which should have the same functionality. Be interested to know if that would suit as we're considering dropping the 'use graphics as pins' functionality from hotgraphic and directing people to use hotgrid instead.
