### ISSUE TITLE
adapt-contrib-vanilla - Add a title font

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_framework#2512]
The vast majority of Adapt themes that I've seen use a separate body and title font. Why not add this into the Vanilla theme so it's easier to apply into other themes

**Comment by oliverfoster** [comment]
Which fonts do you propose?

**Comment by simondate** [comment]
I'm no web designer but we could use one of these combinbations https://artisanthemes.io/best-google-fonts-combinations-modern-agency-website/

We import Open Sans through Google Fonts anyways so wouldn't be too much extra to add.

**Comment by simondate** [comment]
Number 6 uses Archivo with Open Sans

**Comment by oliverfoster** [comment]
> I'm no web designer

I think that's the key phrase.

You can install fonts by making an extension for it and not relying on the open source vanilla theme. Just make one called `adapt-theme-fonts-combination1` etc and add it to your tool?

**Comment by simondate** [comment]
I like to create my themes directly from the Vanilla theme. Maintaining my own theme to create themes from is always a pain as it misses changes and I have to support themes for both clients using v2 and v4.

I'm sure using recommend font combinations from people who are web developers can produce something nice than the current Vanilla theme - https://adaptlearning.github.io/v4demo/

**Comment by oliverfoster** [comment]
> Maintaining my own theme to create themes from is always a pain

You want to shift that burden onto the open source team?

> I'm sure using recommend font combination**S**

How many combinations would you like to include? How can you guarantee that they will satisfy anyone else's requirements? Would you not be better pursuing a font picker in the AAT?

I'll say it again just so I can be sure you didn't ignore it intentionally: How about making an extension for just fonts? It will reduce the burden of having to make an entire theme and allow you to use different font sets.

**Comment by simondate** [comment]
> You want to shift that burden onto the open source team?

Hardly seems like a lot of work. The process to "support" this would be.

1. Import the second font and create a `@title-font` here https://github.com/adaptlearning/adapt-contrib-vanilla/blob/master/less/variables/fonts.less
2. Add `font-family: @title-font` to all the `x-title` here - https://github.com/adaptlearning/adapt-contrib-vanilla/blob/master/less/core/fonts.less

Perhaps it would be good to share this with the community and people who do use the Vanilla theme and see what they think?

**Comment by simondate** [comment]
> How about making an extension for a/some font[s]? It will reduce the burden of having to make an entire theme and allow you to use different font sets.

This seems like a wrong approach. Component and extension development is meant to be de-coupled from the look and the feel of the course. That stuff should all be done through the theme.

**Comment by oliverfoster** [comment]
> This seems like a wrong approach. Component and extension development is meant to be de-coupled from the look and the feel of the course. That stuff should all be done through the theme.

We can only have one theme plugin and one menu plugin at the moment, which I agree is a mistake and an unnecessary restriction as theme and menu plugins share all of the characteristics of the other plugins except the ability to utilise many of them. As subset theme-font plugin would be useful.

Components, extensions, menus and themes are just named plugin sets, their set name is almost entirely arbitrary except that their schemas are handled differently in the case of components.

> Of course if you've had success using this at Kineo I would be happy to hear why you think it's better than adding to the theme.

As you know, we build all themes by hand at Kineo, and this is true of most of the collaborating companies, they are then uploaded to the tool if needed. 

Font sets are almost always chosen according to the client's branding specification and are often proprietary.

> Hardly seems like a lot of work. The process to support this would be.

That's because you've minimised this work to one font again, as it suits your argument. You haven't yet acknowledged that there are many font title/body combinations that people might want to use or that loading / coding those perhaps many font combinations, the majority of which will probably never be used, requires time and resource.

**Comment by oliverfoster** [comment]
Can you do a pr for the `@title-font` bits as described? Just send the variable to `@title-font: @font-family;` rather than add a new font?

**Comment by guywillis** [comment]
https://github.com/adaptlearning/adapt-contrib-vanilla/blob/release/v5/less/_defaults/_font-config.less#L10

https://github.com/adaptlearning/adapt-contrib-vanilla/blob/release/v5/less/_defaults/_font-config.less#L44-L86

**Comment by simondate** [comment]
https://github.com/adaptlearning/adapt-contrib-vanilla/pull/237
