### ISSUE TITLE
adapt-contrib-matching - partial scoring not working

### ISSUE THREAD

**Issue by paul-mediakitchen** [adaptlearning/adapt_framework#2515]
### Subject of the issue/enhancement/features
When the question includes multiple drop downs, the question is not partially scored when user selects the correct option for only some of the drop downs.

The following code implies it should support partial scoring:
https://github.com/adaptlearning/adapt-contrib-matching/blob/master/js/matchingModel.js#L121-L135

### Your environment
Adapt authoring tool v0.8.0
Adapt framework 4.0.1.
Google Chrome latest
Windows PC Windows 10

### Steps to reproduce
Create a course with 2 articles, with an assessment in the first article. The assessment is to include a single Matching component question. Add 2 drop downs to this question.
Add an assessment results component to second article.

### Expected behaviour
I expected the score if I got one out of 2 correct to be 50% of the total score but it was zero

### Actual behaviour
It scored the question zero

### Screenshots (if you can)
![matching_partial_correct](https://user-images.githubusercontent.com/10856676/64121284-4d77dc00-cd96-11e9-8b27-77685ea312b4.jpg)

**Comment by oliverfoster** [comment]
I agree.

Mcq/gmcq base ignores isCorrect: https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/models/itemsQuestionModel.js#L102

Slider ignores isCorrect: https://github.com/adaptlearning/adapt-contrib-slider/blob/master/js/sliderModel.js#L130

TextInput ignores isCorrect: https://github.com/adaptlearning/adapt-contrib-textInput/blob/master/js/textInputModel.js#L178

Assessment doesn't count scores when isCorrect = false, so aligning matching won't change assessment behaviour:
https://github.com/adaptlearning/adapt-contrib-assessment/blob/master/js/adapt-assessmentArticleModel.js#L459

**Comment by kevindoherty30** [comment]
@oliverfoster so if the assessment doesn't count scores when isCorrect = false, then what extra benefit is there to partial scoring on those components? What would happen with those partial scores when used in an assessment?

Or would this require a separate results component that could combine partial scores to give an overall assessment score?

**Comment by oliverfoster** [comment]
There needs to be some additional work to the assessment to get it to count partial scores when requierd but that can't happen without the former work.

**Comment by paul-mediakitchen** [comment]
Just to clarify, does the Matching Question require additional work to the assessment to count partial scores? Or are you referring to MCQ ?

**Comment by paul-mediakitchen** [comment]
@oliverfoster - is it a major change to the assessment or just a case of an additional clause for if (question.get('_isPartlyCorrect') etc?
I am thinking the question could have a setting to specify if it wants to support partial scoring or not.
Hence in the questions internal setScore function it may require an extra conditional?

**Comment by oliverfoster** [comment]
I'd prefer that the assessment allowed partial scoring in the sum rather than us controlling it at an individual question component level; which should be relatively simple  with a new clause and config flag, as you've articulated, at https://github.com/adaptlearning/adapt-contrib-assessment/blob/master/js/adapt-assessmentArticleModel.js#L459.

Partial scoring has its own oddities, in that it is possible to pass an assessment by answering all of questions incorrectly, as long as the score they emit passes the threshold. 
i.e. Assessment score to pass = 50%; Matching with 4 rows, 2 correct, 2 incorrect, question failed, assessment passed.

Are there any assessment use-cases you can think of where some questions should be partially scored and others not?

I think that questions should always produce a partial score but that the assessment should sum the scores according to:
```js
var includeQuestionScore = _isQuestionComplete || _isAssessmentPartialScoring;
score += includeQuestionScore ? _questionScore : 0;
```

**Comment by paul-mediakitchen** [comment]
Thanks @oliverfoster - a global setting for allowing partial scoring works fine for me and makes much more sense on reflection.

With regards your comment about passing an assessment by answering all of the questions incorrectly - by incorrectly you mean they did not select all the correct answers for each question? But if they have enabled partial scoring then they accept the fact a question will still add to the overall score if it is partly correct. This isn't a problem with the matching question but it would  not be ideal if a MCQ that had 3 out of 4 options correct and the user was able to select all 4 to score 100% for that question.

**Comment by oliverfoster** [comment]
> by incorrectly you mean they did not select all the correct answers for each question

Yup.

> This isn't a problem with the matching question but it would not be ideal if a MCQ

Surely it's the same issue regardless of the question type? It ends up looking a bit weird if question marking is on, such that each question has a red cross but the final message is a confirmation of success.

**Comment by paul-mediakitchen** [comment]
![matching_partial_correct](https://user-images.githubusercontent.com/10856676/64162835-f75b7500-ce37-11e9-80be-3880fea8c67d.jpg)

With the matching question, each drop down is in effect almost a separate question and you can only select one option or the other - you can't select them all to try and include the correct option in the mix. So getting a score for each one you get right makes more sense.
I understand what you are saying though if the question has an X to indicate the user has got the overall question wrong.

**Comment by oliverfoster** [comment]
![image](https://user-images.githubusercontent.com/7974663/64163340-fe36b780-ce38-11e9-8d29-c457a4a1bf7d.png)

Isn't this identical to the mcq and gmcq?

**Comment by paul-mediakitchen** [comment]
![true_false](https://user-images.githubusercontent.com/10856676/64164003-31c61180-ce3a-11e9-8bb0-58b817fadf05.jpg)

With the type of question I want to replicate, the user must make a decision for each statement whether it is true or false.

**Comment by oliverfoster** [comment]
I see. You probably also need multi-item correctness specific feedback as well.

**Comment by paul-mediakitchen** [comment]
In my example the user is unable to select both a wrong answer and a correct answer for a particular statement

**Comment by paul-mediakitchen** [comment]
The feedback can probably just be done as in my example tho it would need to cope with randomisation of the answers

**Comment by oliverfoster** [comment]
The trouble with the feedback is that, by this example, you'll need to determine which **items** in the matching were correct or incorrect. Adapt questions have feedback only based upon **question** correctness not **item** correctness. So partial scoring isn't going to help solve your itemised feedback issue. 

Assuming you want this type of feedback:
![](https://user-images.githubusercontent.com/10856676/64164003-31c61180-ce3a-11e9-8bb0-58b817fadf05.jpg)

**Comment by paul-mediakitchen** [comment]
In my example the feedback lists all 5 statements and displays the correct answer regardless of what answer the user selected. Let me quicky mock this up using my Adapt apple grape example

**Comment by oliverfoster** [comment]
That makes sense.

**Comment by paul-mediakitchen** [comment]
With the MCQ, if there are 4 answers and 3 of these are correct.
Option 1. Allow only 3 answers to be selected - prevents user selecting them all but gives a clue to how many correct answers there are
Option 2: Allow all 4 answers to be selected - user can just select them all without any penalty

Option 1 is the better option when partial scoring has been enabled

**Comment by paul-mediakitchen** [comment]
I wasn't aware you could use variables in the feedback. Thought was only possible in the assessment results

**Comment by paul-mediakitchen** [comment]
It isn't the end of the world if the feedback doesn't say something like **4 out of 5 correct**

The user will see the ticks and crosses and the feedback text can say "Partially correct"

**Comment by paul-mediakitchen** [comment]
@oliverfoster why does the assessment calculate the score again even though the question has its own function to set the score?

**Comment by oliverfoster** [comment]
Assessment is a collection of questions, it aggregates the scores of many questions, it acts as a set of questions with a current aggregate and a max aggregate score which is either passed or failed according to single threshold. Assessment aggregates question scores not question item scores.

**Comment by paul-mediakitchen** [comment]
Thanks @oliverfoster - I could see the Matching Question was setting the value of _score on the question model but wasn't sure where this _score value was being used if it is not being used in the Assessment itself. I probably just need to look harder

**Comment by oliverfoster** [comment]
Question _score isn't currently used in the assessment. The assessment takes the questionWeight and isCorrect value and assumes that if the question is correct it'll be assigned the value of questionWeight (default: 1); the score is considered to be either full off or full on based upon correctness (0 or 1). Partial scoring will change the binary correctness to a range of correctness, such that _score is used a proportion of _questionWeight. The score use by the assessment would be 0 **to** questionWeight (0-1 with a default question weight) instead of 0 **or ** questionWeight.

**Comment by paul-mediakitchen** [comment]
@oliverfoster thank you very much for the detailed notes on the current implementation and suggested solution. If I have understood you correctly the question _score is not used at all and is redundant? But was possibly implemented for future use? Apologies if I have misunderstood this (which is highly likely)

I hope I haven't opened a can of worms here. I was just trying to replicate the scoring in our other tool so we could encourage people to use Adapt as an alternative tool.

It sounds like it is quite an undertaking to implement this partial scoring and will involve changes to the core plus each of the question components too.

Still not sure if having the partial scoring as a global setting is ideal as whilst partial scoring may be appropriate for matching question types, it may not be appropriate for MCQ and GMCQ. If it wasn't a pain to offer the ability to set the partial scoring setting in the question itself I think it would offer more flexibility. In our other tool, MCQ questions are not partially scored. If you select all the correct options and no incorrect options you get full marks. If you only select all the correct options plus a wrong option you get zero. If you select only some of the correct options and no incorrect options you get zero. I can understand how this could be considered inconsistent.

Your suggested scoring for the partial scoring (certainly for matching) matches my thoughts where the score is simply the number of correctly selected items as a proportion of the number of correct items hence a percentage value that is applied to the weighting for the assessment calculations.

I will take a look at the other thread. Perhaps this can help generate some momentum.

Thanks again

**Comment by oliverfoster** [comment]
> If I have understood you correctly the question _score is not used at all and is redundant

We'd have to do a bit more research into it, I'd imagine it's used in some components internally as part of the correctness check, but yes it's certainly redundant in the assessment.

> I hope I haven't opened a can of worms here.

No, the can was already open, it was just going stale in a corner.

> It sounds like it is quite an undertaking to implement this partial scoring and will involve changes to the core plus each of the question components too.

Yes, perhaps, all the more reason to get it right this time - it hasn't really changed since Adapt's inception.

It may be that implementing the `getMaxScore` and `getScore` functions as I'd described, where max-score is an integer count of the available correct options, and `getScore` is an integer portion of 0-max-score (rather than a ratio of `questionWeight`) is a lot easier and less backward incompatible than I have implied. This is as you may be entirely right and in the _question score being unused and redundant_ - which would make the attributes immediately available for use with no negative impact.

With regards to MCQ + GMCQ, I would prefer not to assume designer requirements nor create exceptions to rules which could otherwise easily be globally available. Perhaps on each question we should have `_partialScore = "inherit" | "yes" | "no"` such that by default partial scoring is inherited from an assessment or is disabled by assumption otherwise it is explicitly enabled or disabled.

**Comment by oliverfoster** [comment]
This can be revisited once https://github.com/adaptlearning/adapt_framework/pull/3172 is merged
