### ISSUE TITLE
Drawer's .drawer-holder has incorrect ARIA role when there's only 1 item in the drawer

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#2517]
If your course only has one extension that adds something to the drawer - or uses PLP - then the `.drawer-holder` element has a role of `"list"` - but has no children with a role of `"listitem"`:
![2019-09-06 16_51_54-Developer Tools - Mental Fitness _ Train your brain toolkit - http___localhost_3](https://user-images.githubusercontent.com/1249597/64442161-3ce1a180-d0c7-11e9-861d-91619f1e019f.png)

The `role=list` attribute needs to be removed when there's only one item in the drawer.

**Comment by moloko** [comment]
I've also just spotted in that screenshot that the `.drawer` element has the attribute `aria-labelledby="drawer-heading"` - but I think that might not exist?

**Comment by eleanor-heath** [comment]
Both of the above issues seem to be resolved (I am using FW 5.13.0), see screenshot below.
![Drawer incorrect aria role](https://user-images.githubusercontent.com/61159216/119478719-f2df9a00-bd47-11eb-94ab-40fe6ced1ce1.png)

I have one item in the drawer; the search extension. I did notice another issue where the search title reads out Search, Empty group. This seems to be caused by the tabindex thats applied to the dawer__item-title-inner.

**Comment by eleanor-heath** [comment]
I have raised another issue for the bug I spotted as it is a search extension specific bug. ****https://github.com/adaptlearning/adapt_framework/issues/3157

@oliverfoster I haven't been able to replicate this issue.
