### ISSUE TITLE
pageLevelProgress - animation on bar removed since v2

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt_framework#2562]
I'm in the process of upgrading a theme from v2 to v4 of the FW and I noticed that the v2 theme has an animation effect when you complete a component and this was absent in v4. As you can see from the attached gifs, it seems that v4 deletes and recreates the element each time rather than changing the CSS values as it did previously in v2 of the FW.

## v2

![v2](https://user-images.githubusercontent.com/1676635/67663211-8fd52800-f997-11e9-9ad2-d0b05a66cc40.gif)

## v4

![v4](https://user-images.githubusercontent.com/1676635/67663215-91065500-f997-11e9-8379-3e42d4b03839.gif)

**Comment by guywillis** [comment]
Hi @simondate,

This issue was identified very late on during the development of v5 and subsequently fixed but only for that version. 

Here is the commit with the fix: https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/commit/0ea56d8501e37f4f2de158123df6968f95fff147

There will be some development required to port, and amend, the changes from the v5 version to v4 - is this something you'd be able to help with?

**Comment by guywillis** [comment]
Can I close this issue?

**Comment by simondate** [comment]
@guywillis yeah just close it
