### ISSUE TITLE
Notify obstructing access to content

### ISSUE THREAD

**Issue by chris-steele** [adaptlearning/adapt_framework#2579]
### Subject of the issue/enhancement/features
Notify popups that exceed available screen height cannot be scrolled (on non-touch devices). In Firefox a secondary scrollbar appears and it is possible to drag this scrollbar or use the page up/down keys to scroll the entire popup, but mouse wheel and cursors cannot be used. In IE11 and Chrome there is no secondary scrollbar and there is no method to scroll through the popup.

### Your environment
* version v4.4.x, release/v5
* all browsers
* all platforms

**Comment by chris-steele** [comment]
@oliverfoster after a little consideration I could do with your eyes on this issue if possible?

**Comment by oliverfoster** [comment]
Could you split into 2 separate issues?

**Comment by oliverfoster** [comment]
![popup_scroll](https://user-images.githubusercontent.com/7974663/68775794-f9effd00-0626-11ea-9ef7-da382bd2c74d.gif)

I can't replicate in 4.4 on Firefox, Chrome or IE11 with a normal but large bodied notify. Can I have some more context?

**Comment by chris-steele** [comment]
Looks like the context is hot graphic (or components like it that use a notify subview).

**Comment by oliverfoster** [comment]
prevent scroll [here](https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/a11y/scroll.js#L197-L199) checks for `pointer-events: none;` which is present [here](https://github.com/adaptlearning/adapt-contrib-hotgraphic/blame/master/less/hotgraphic.less#L55) in the hotgraphic styling.
That styling is needed so that the click events trigger on the notify shadow for the notify close event, as the hotgraphic styling is so different from the usual notify in that it isn't full width, the user might expect to click the empty space either side of the hotgraphic dialogue to close the popup.

**Comment by guywillis** [comment]
I believe the pointer-events issue is only present in v4 of the framework. I have tested v5 and cannot replicate the pointer events issue (they've been removed).

The vertical alignment issue is present in both v4 and v5 of the framework.
