### ISSUE TITLE
Styling of menu differs when scrolling container enabled

### ISSUE THREAD

**Issue by tomgreenfield** [adaptlearning/adapt_framework#2710]
### Subject of the issue/enhancement/features
There is no top padding on the course root menu if the scrolling container is enabled.

### Your environment
* Framework 5.3, authoring tool 0.10.3
* Chrome 80
* Windows 10

### Expected behaviour
Not sure which styling is intended.

### Screenshots (if you can)

`_scrollingContainer._isEnabled = false` | `_scrollingContainer._isEnabled = true`
-- | --
![normal](https://user-images.githubusercontent.com/922987/78030858-aa526980-735a-11ea-95ee-5300771a99fc.png) | ![scrolling](https://user-images.githubusercontent.com/922987/78030873-af171d80-735a-11ea-804d-eaf0e6560cb5.png)

**Comment by NayanKhedkar** [comment]
Hi @tomgreenfield , I have tried to replicate the same, but I didn't  get any top padding difference while toggling (true/false) scrolling container.

**Environment:**
Framework 5.3
Chrome 80
Windows 10

![image](https://user-images.githubusercontent.com/16237837/78893897-ba202b00-7a89-11ea-867c-b5e6f3986dd6.png)

**Comment by guywillis** [comment]
From what I can tell everything is working as intended and suspect the variance in height is due to the navigation bar not being present.

When `_scrollingContainer._isEnabled = false` the default styling is applied whereby the wrapper gets top padding of 3.5rem and the navigation bar is fixed creating a consistent approach regardless of menu / page the user is on and whether there is a nav bar or not.

When `_scrollingContainer._isEnabled = true` the wrapper padding top gets set to 0 and the nav bar's position is relative. This approach won't make a difference visually when the nav bar is present but will move the wrapper and content upwards when the nav bar is not present. 

https://github.com/adaptlearning/adapt_framework/blob/master/src/core/less/core/scrolling.less

**Comment by tomgreenfield** [comment]
Just to add information regarding the original issue: the calculated height is also wrong when the navigation bar isn't present with the scrolling container enabled.
