### ISSUE TITLE
CVS delimiter detection is wrong on importing csv language files 

### ISSUE THREAD

**Issue by notz** [adaptlearning/adapt_framework#2853]
### Subject of the issue/enhancement/features
The csv delimiter detection introduced in #2737 is not working correctly. 
The introduced regex can't work correctly:

         const firstLineMatches = fileContent.match(/.+\/"{0,1}.{1}/);

It probably should look like:

        const firstLineMatches = fileContent.match(/.+\/"{0,1}[,;\t]{1}/);

Reference: https://github.com/adaptlearning/adapt_framework/blob/3f25a4d26eee849771478f8f0f1b3847b64f0885/grunt/helpers/Translate.js#L297

**Comment by oliverfoster** [comment]
How is it not working correctly? What issue are you trying to solve?

**Comment by notz** [comment]
The regex is matching any character.

.+ -> min 1 char 
\"{0,1} -> must not match 
.{1} -> on char 

So it can match on any place after the first char

**Comment by oliverfoster** [comment]
Can you post the first line of your csv? I want to find something more fitting.

**Comment by notz** [comment]
I can't post they complete line because it's a private project. But it's like that:

    "articles/5e857dd5f99bb68c5cbf6515/body/","<p><strong>Le client est en ligne</strong></p>

**Comment by oliverfoster** [comment]
Yea that makes sense.

**Comment by oliverfoster** [comment]
Yea, you suggestion of limiting the delimiters seems like the only sensible option. [The article](https://en.wikipedia.org/wiki/Delimiter-separated_values) suggests pipe and space should be included and we can probably drop the rest of the regex an just match the delimited list directly.  `/[,;\t| ]{1}/`

**Comment by notz** [comment]
The best is to use this https://www.npmjs.com/package/detect-csv or this https://www.npmjs.com/package/csv-string#detectinput--string--string

With the regex their may still be a problem. Detection should also only be done if **not** defined via command line.

**Comment by oliverfoster** [comment]
I completely disagree about using a library to do this, both of these libraries detect delimiters in ways that are almost identical to a regex [detect-csv](https://github.com/finnp/detect-csv/blob/master/index.js#L1-L43), [csv-string](https://github.com/Inist-CNRS/node-csv-string/blob/master/src/CSV.ts#L57-L65) and they are both designed for generic data. In contrast, we know what the data looks like on the first line of all of these files.

To have detection only be done if not defined at the command line change [this line](https://github.com/adaptlearning/adapt_framework/blob/3f25a4d26eee849771478f8f0f1b3847b64f0885/grunt/tasks/translate.js#L16) to default `null` instead of a comma then check for `null` before [this line](https://github.com/adaptlearning/adapt_framework/blob/3f25a4d26eee849771478f8f0f1b3847b64f0885/grunt/helpers/Translate.js#L297).
