### ISSUE TITLE
adapt-contrib-vanilla: responsive block padding?

### ISSUE THREAD

**Issue by kirsty-hames** [adaptlearning/adapt_framework#2863]
Currently Vanilla sets the same value for block padding regardless of screen width. With `@block-padding-ver` set at a default value of 4rem that's 8rem of space between blocks of content for a small screen. 

I end up adding a media query on all projects now to resolve this.

```
  &__inner {
    .l-container-padding(@block-padding-ver, @block-padding-hoz);

    @media (max-width: @device-width-small) {
      .l-container-padding((@block-padding-ver / 2), (@block-padding-hoz / 2));
    }
  }
```
Is it worth adding a media query into Vanilla? I also find this the case for `.page__header-inner`

**Comment by guywillis** [comment]
The default block padding vertical value was chosen to give enough space for trickle to render below a component without overlapping the content, any reduction of this value will cause this overlap to reappear.

**Comment by kirsty-hames** [comment]
Thanks @guywillis I didn't realise that. Seeing as Trickle is an extension though would it make sense to have a generic block padding in core/block.less and a Trickle specific padding in plugins/trickle.less?

If I didn't have Trickle enabled in a course it shouldn't determine my padding size.

**Comment by guywillis** [comment]
It could be the way to go.

The original reasoning was to keep a consistent block padding, responsively, that would be able to support additional elements on screen such as Trickle and not introduce uneven layouts.

4rem was chosen because it was close to the previous value of 60px and large enough to contain the trickle button (42px) with some spacing leftover. (and it's a nice round number :))
