### ISSUE TITLE
adapt-contrib-matching and adapt-contrib-textInput: Submit buttons do not work

### ISSUE THREAD

**Issue by rschweigert** [adaptlearning/adapt_framework#2868]
Tested in a AF standard installation (v5.6.1).

### Your environment
* AF v5.6.1
* adapt-contrib-matching v4.0.1
* adapt-contrib-textInput v4.0.0
* tested in firefox (v 79.0) and chromium (v 84.0.4147.105) with all add-ons disabled
* OS: Kubuntu 18.04

### Steps to reproduce
Install a new course with _adapt create course_, build and launch new course and check second part: _Question Components_

**Comment by moloko** [comment]
@rschweigert this should work fine if you either:
* use the master branch of either plugin, or
* use the v5.6.1 release of the FW instead of the master branch (`adapt create course` defaults to using the master branch unless you tell it otherwise)

The next release of these two question components should resolve this issue.

**Comment by rschweigert** [comment]
Thank you!

**Comment by moloko** [comment]
should be resolved with FW v5.7.0
