### ISSUE TITLE
adapt-devtools: Unlock button no longer works

### ISSUE THREAD

**Issue by swashbuck** [adaptlearning/adapt_framework#2870]
### Subject of the issue/enhancement/features
In Adapt v5 using Dev Tools v3.0.3, the Unlock button throws an error and does not unlock locked topics:

`Uncaught (in promise) TypeError: e.ownerDocument is undefined`

### Your environment
* Adapt Framework v5.6.1
* Tested in Mac High Sierra: Firefox 79, Chrome 84

### Steps to reproduce
Set up a menu and sequential locking ( "_lockType": "sequential" ).  Open Dev Tools and click "Unlock".

### Expected behaviour
Locked topics should unlock

### Actual behaviour
Javascript error

**Comment by moloko** [comment]
@swashbuck this should have been fixed by #2852 - could you check the latest master branch of the FW to see if that resolves it?

**Comment by moloko** [comment]
original issue: https://github.com/cgkineo/adapt-devtools/issues/46

**Comment by moloko** [comment]
minor note: you should log issues with non-core plugins on the repo for the plugin... 

in this instance the problem was actually in the FW itself - when that's the case the plugin owner should be responsible for finding that out and logging it - as Chris did [here](https://github.com/adaptlearning/adapt_framework/issues/2851)

**Comment by swashbuck** [comment]
Thanks, @moloko .  Updating the framework fixed the issue.  I will also make a note about where to log future tickets (thanks for the tip!).
