### ISSUE TITLE
adapt-contrib-hotgraphic: unimplemented setting _items._ariaLevel

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#3027]
Looks to have been introduced via https://github.com/adaptlearning/adapt-contrib-hotgraphic/pull/155 - but doesn't actually look to have been implemented anywhere in the code/templates - the only two references to it are in README.md and properties.schema

Pretty sure it should just be removed - any objections?

**Comment by oliverfoster** [comment]
[This line in the template](https://github.com/adaptlearning/adapt-contrib-hotgraphic/blob/master/templates/hotgraphicPopup.hbs#L10) should cause [this line in the helper 'a11y_attrs_heading'](https://github.com/adaptlearning/adapt_framework/blob/master/src/core/js/helpers.js#L349) to fix the aria level of the popup heading to that set in the item due to the nature of the `this` context as [this line](https://github.com/adaptlearning/adapt-contrib-hotgraphic/blob/master/templates/hotgraphicPopup.hbs#L3)

**Comment by moloko** [comment]
Ah, I see - makes sense now
