### ISSUE TITLE
The 'grunt watch' eats over 50% of CPU

### ISSUE THREAD

**Issue by LukaszGrela** [adaptlearning/adapt_framework#511]
I have noticed that my CPU stats were going sky high, the problem was that most of it ate node.exe with over 50% usage, there was nothing running except the grunt server and grunt watch. I have tried both separatelly and only grunt watch was eating CPU, it starts with around 22% and climbs even when nothning is done to the files it watches, after 30mins I have 57% which tends to drop to 48% and climb back..

**Comment by taylortom** [comment]
Do you have the latest version of the package.json? We've recently upped the version of grunt and grunt-config-watch (look for ~0.4.5 and ~0.6.1 respectively).

**Comment by LukaszGrela** [comment]
I have the `"grunt-contrib-watch": "~0.5.1"` in the package.json how to update it? do I have to create new course and move the content of src folder across?

**Comment by taylortom** [comment]
You just need the latest package.json, so you can get this by updating the git repo, or downloading directly from here: https://raw.githubusercontent.com/adaptlearning/adapt_framework/master/package.json, then running `npm update`

**Comment by LukaszGrela** [comment]
It seem to be OK - I had soem `npm WARN` but no errors and content works fine, and usage fluctuates from 0 to 10+% but always drops to 0

**Comment by taylortom** [comment]
Ah ok cool :)
(For future reference, this was fixed in https://github.com/adaptlearning/adapt_framework/pull/496)

**Comment by JeromeLam** [comment]
@taylortom if you mean that the fix may not be all that useful, I think I agree.  I'm experiencing CPU utilization between 60% and 85% at all times.

Only by cutting down the number of sub-tasks (under *watch* in [Gruntfile.js](https://raw.githubusercontent.com/adaptlearning/adapt_framework/master/Gruntfile.js)) can I bring the CPU utilization down.  This can also be problematic in a scenario where we have a large quantity of components or extensions since an unbounded amount of assets will be watched.  I'm in favor of a change to the number/type of files and folders being watched.
