### ISSUE TITLE
Add LESS Mixins

### ISSUE THREAD

**Issue by LukaszGrela** [adaptlearning/adapt_framework#515]
Can the LESS Elements be added to the framework?

**Comment by oliverfoster** [comment]
Indeed they can. 

You can do this by either extending or creating a LESS file in:

The theme/adapt-contrib-theme/less folder (example: https://github.com/adaptlearning/adapt-contrib-vanilla/tree/develop/less)
Or you can add it to an new extension by putting your mixins in the /less folder inside your extension. (example: https://github.com/adaptlearning/adapt-contrib-resources/tree/develop/less)
Or you can just extend the src/core/less files. (https://github.com/adaptlearning/adapt_framework/tree/develop/src/core/less)

You can provide your own core/theme/extension on github online for others to use, and these can forked (or not) from a preexisting item. 
You can also submit a PR (pull request) if you have an idea that you think the community might like and you believe it should be included in the Adapt project. (You should probably strike up a conversation in the community forum first https://community.adaptlearning.org/login/index.php so that others can get engaged with your idea.)

If you submit a PR, remember that:

The core is global (for all of us, all the time)
An extension is very specific (a project builder has to elect to use the extension before its behaviour/styling/templates becomes available).
A theme is somewhere in between (covering all components and extensions when we use the theme in our projects)

**Comment by LukaszGrela** [comment]
thanks for detailed description - when I was trying to do it I've failed miserably:) now I should have more luck

**Comment by oliverfoster** [comment]
I hope so, it's not at all hard once you get it. It's just a steep learning curve. Have fun, let us/me know how you get on.

**Comment by zenduo** [comment]
Are mixins going to be added to core or should this one be closed?

**Comment by oliverfoster** [comment]
This can be closed, it was just whether less mixins can be used. the answer is yes.
