### ISSUE TITLE
Revert Gruntfile.js to build all menus/themes by default

### ISSUE THREAD

**Issue by taylortom** [adaptlearning/adapt_framework#536]
Has been recently updated so that it falls over if a theme other than 'adapt-contrib-vanilla' or a menu other than 'adapt-contrib-boxMenu' is used.

**Comment by LukaszGrela** [comment]
+1
whenever user is chaning the theme or menu the `adapt install/uninstall` is done, could it be automated so after install/uninstall of the theme or menu the "config" file was updated and then `Gruntfile.js` would pick the values from the config instead of the taking it from arguments?
`grunt build --theme="new-theme-name" --menu="new-menu-name"`

**Comment by brian-learningpool** [comment]
This should indeed be pulled in from the config.  In the adapt_authoring project this can be retrieved by the `_theme` and `_menu` attributes in `config.json`.

**Comment by dancgray** [comment]
+1 This causes us quite a few problems, most of our projects have a custom themes and menus.

**Comment by zenduo** [comment]
Moved to https://adaptlearning.atlassian.net/browse/ABU-473
