### ISSUE TITLE
Console logging warnings about depreciated Backbone options

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#641]
I've noticed this output on the latest test package:

`Depreciated - Using backbone options functionality`

**Comment by moloko** [comment]
Seem to recall this was something @oliverfoster added to show where people needed to update their code.
It's something to do with the more recent version of Backbone we're using now no longer supporting the way we were instantiating views
So, it's meant to be here - what we do need to do I guess is log all the instances it's referring to so that people can update their code. Unfortunately you can't really do this at the moment because the test package code is minified

**Comment by moloko** [comment]
Also if someone could correct the spelling to 'deprecated' that would make me happy ;-) (Oh, and 'instantiated'...)

**Comment by oliverfoster** [comment]
https://adaptlearning.atlassian.net/browse/ABU-946
