### ISSUE TITLE
The accessibility property in config.json/course.json is inconsistent

### ISSUE THREAD

**Issue by brian-learningpool** [adaptlearning/adapt_framework#643]
Regarding the `_accessibility` property in `config.json,` this has an `_isEnabled` attribute, which is consistent with how other extensions are implemented, i.e. since it can be toggled. However, in the `develop` branch for v2.0 right now, the entire attribute seems to have moved to `course.json` and  `_isEnabled` seems to be used as an 'active' flag, rather than to enable or disable the feature.

I'm proposing that we:
* standardise the location of this attribute in one place
* ensure that `_isEnabled` allows fully disabling accessibility if it is not required 
* possibly introduce an `_isActive` property

**Comment by brian-learningpool** [comment]
@oliverfoster, any thoughts on this one?

**Comment by oliverfoster** [comment]
Yea, it's quite long winded. We need to change all current references to config._accessibility._isEnabled to _isActive, then work on disabling it entirely.

**Comment by oliverfoster** [comment]
Disabling is somewhat multifaceted and because this is all very prototypeish it really needs a map of what is actually going on - to come as part of a greater explanation of accessibility.

For the moment though, there are parts of the popup manager that need to remain active to  maintain tabindex values and the text post-processor can be turned off entirely.

So - 
Text post-processor ($.a11y_text): off
Tabindex / Popupmanager: on

**Comment by brian-learningpool** [comment]
@oliverfoster, I think this can be closed now with this PR #647?

**Comment by oliverfoster** [comment]
yea, we're a million miles from where we were.
