### ISSUE TITLE
Separate config files by lesson/page

### ISSUE THREAD

**Issue by imjosecampos** [adaptlearning/adapt_framework#776]
Is there a way to have multiple articles.json, blocks.json and components.json so that I can separate the content in pages/lessons?

**Comment by oliverfoster** [comment]
Not at the moment I'm afraid. Although it has been talked about a few times.

**Comment by jscampos** [comment]
Thanks if I come up with any useful ways to get this working I will post it here.

**Comment by oliverfoster** [comment]
Brilliant. With no amends to the framework you'll have to keep the children together for each major section so that adapt can keep the rendering order. All pages together for one menu, all articles for a page, etc. This is so that the child order in the json appears as it should. Of course, with amends to the framework it could be done in any way. Good luck.
