### ISSUE TITLE
Accessibility documentation

### ISSUE THREAD

**Issue by moloko** [adaptlearning/adapt_framework#904]
copied from [ABU-1103](https://adaptlearning.atlassian.net/browse/ABU-1103)

**Comment by chris-steele** [comment]
Draft sent to @chucklorenz for review and hopefully conversion to a Wiki page.

**Comment by chucklorenz** [comment]
[Jump to pages under construction.](https://github.com/chucklorenz/demo-wiki/wiki/Accessibility-Menu)

**Comment by moloko** [comment]
good stuff @chucklorenz 

I think it would also be useful to have an overview of:
* designing accessible courses (both visual style i.e. choosing readable fonts, displaying them at a readable size, using contrasting foreground & background colours - and also writing style)
* testing courses for accessibility (I'm sure the Kineo QA team could be persuaded to write something about this
* an idea of how much additional effort is required to make an Adapt course accessible - a lot of people seem to think that it requires little or no extra work!

No need to provide a comprehensive guide, just a good, high-level, overview with links to other resources where appropriate

I'm keen to emphasise that the technical aspect of accessibility is only part of the whole picture

**Comment by chucklorenz** [comment]
> I'm keen to emphasise that the technical aspect of accessibility is only part of the whole picture  

I'm with you @moloko . This is a broad topic that I think will warrant more than one effort. I think my first pass will lay-down the basics for both the end-user and developer, in order to fill in the documentation gap quickly/soon. I have two good docs to guide me (and from which I intend to plagiarize liberally!): _Adapt Accessibility Standards and Guidelines_ that I believe made its way to me via Paul Welch and _Accessibility in Adapt: A technical perspective_ that @chris-steele passed to me. A second pass can delve into accessible course design and testing with JAWS, etc. Interesting how big a role iPad is playing in the low-vision communities. I think we have to pay as much attention now to how VoiceOver processes HTML as we do JAWS.   
This issue is not going away for me any time soon. I have a meeting tomorrow to talk Adapt with a friend who serves as a chair on [RESNA](http://www.resna.org/about)'s certification committee.

**Comment by chucklorenz** [comment]
A new wiki article for [Accessibility](https://github.com/adaptlearning/adapt_framework/wiki/Accessibility) is live. Please critique and/or directly edit.

@oliverfoster During the run-up to the v2 release, Paul Welch delivered to me _Adapt Accessibility Standards and Guidelines_. I believe that you will recognise it. I do not know who wrote it, so I do not know whom to ask for permission to post it publicly. The document is stored in the documentation repo and linked in two places in the Accessibility main article including the Resources section. Can you help me track down the author or authorization to post?

@chris-steele You will find that the document you provided is stored in the documentation repo and linked in two places in the Accessibility main article including the Resources section. I couldn't figure out a better way to integrate its content more organically. I remain open to suggestions. 

@moloko I recommend retaining your suggestions for fuller documentation. Before we close this ticket, can they be transferred to a new one to be placed in backlog?

**Comment by oliverfoster** [comment]
@kineopete ^ can you let chuck know he's fine to publish our accessibility stuff publicly
